spring.application.name: demo

spring:
  datasource:
    url: jdbc:h2:mem:testuserdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      max-lifetime: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

