# 워크플로우 이름 정의
name: CI/CD

# 워크플로우 트리거 조건
on:
  push:
    branches:
      - "main"    # main 브랜치에 push될 때
      - "develop" # develop 브랜치에 push될 때
  pull_request:
    branches:
      - "main"    # main 브랜치로 PR 생성될 때
      - "develop" # develop 브랜치로 PR 생성될 때

# 전역 환경 변수 설정
env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_BUILDKIT: "1"

# 실행될 작업들
jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      # 소스 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle' # Gradle 캐시 활성화로 빌드 속도 향상

      # Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: ./demo
        run: chmod +x gradlew

      # Gradle 빌드 실행 (테스트 제외)
      - name: Build with Gradle
        working-directory: ./demo
        run: ./gradlew bootJar -x test

      # 빌드된 JAR 파일을 아티팩트로 저장
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: demo/build/libs/*.jar

  # 테스트 작업
  test:
    needs: build  # 빌드 작업이 성공적으로 완료된 후에 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      # 이전 빌드 작업에서 생성된 JAR 파일 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: demo/build/libs

      # Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: ./demo
        run: chmod +x gradlew

      # 테스트 실행
      - name: Run tests
        working-directory: ./demo
        run: ./gradlew test

      # 테스트 결과를 아티팩트로 저장
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # 테스트 실패 시에도 결과 저장
        with:
          name: test-results
          path: |
            demo/build/reports/tests/test/
            demo/build/test-results/test/

  # 배포 작업
  deploy:
    needs: [build, test]  # 빌드와 테스트가 모두 성공적으로 완료된 후에 실행
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 빌드된 JAR 파일 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: demo/build/libs

      # Docker 이미지 태그 버전 설정
      - name: Set version
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      # AWS 접근을 위한 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # AWS 서울 리전

      # Amazon ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Docker 이미지 빌드 및 ECR 푸시
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          DOCKER_BUILDKIT: "1"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.VERSION }} -f demo/Dockerfile demo/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.VERSION }}

      # ECS 서비스 업데이트하여 새 버전 배포
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --force-new-deployment
